spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/StarPxc/config-repo
          username: starPxc
          password: 935377012pxc
          basedir: E:\Software installation path\configGitRepository
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
server:
  port: 8002
management:
  security:
    enabled: false
