eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/ #注册到另一个注册中心
    register-with-eureka: false #不把这个设置成false自己要向自己注册
  instance:
    hostname: clientName
  server:
    enable-self-preservation: false
spring:
  application:
    name: eureka
server:
  port: 8761

