eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: order
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 935377012
      url: jdbc:mysql://127.0.0.1/SpringCloud_shell?characterEncoding=utf-8&useSSL=false
  jpa:
      show-sql: true
server:
  port: 8001
PRODUCT:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule